"""AISHA REST API: the same guarded agent pipeline as the Streamlit app.

Run:  uv run uvicorn stai.api:app --reload
Docs: http://localhost:8000/docs (OpenAPI, generated by FastAPI)

Endpoints:
- ``GET /health``  liveness + knowledge-base/model status.
- ``POST /chat``   one guarded agent turn for an employee.

Conversation memory: if the request carries no ``history``, the last few
persisted turns from the ``chat_messages`` table are used, and every turn is
persisted back - so API conversations survive restarts. Passing an explicit
``history`` makes the call stateless (it is still persisted).

The ``sim_date`` field is the demo's simulated clock (same as the Streamlit
sidebar); it defaults to the server's current date only when omitted, and all
agent/pulse logic downstream receives it explicitly.

LLM dependencies (``get_agent_llm`` / ``get_guardrail_llm``) return ``None``,
meaning "build the default Ollama models"; tests override them with fakes via
``app.dependency_overrides`` so no Ollama is needed.
"""

from __future__ import annotations

from datetime import date
from functools import lru_cache
from typing import Literal

from fastapi import Depends, FastAPI, HTTPException
from pydantic import BaseModel, Field

from stai.config import settings
from stai.service import HISTORY_LIMIT, run_chat_turn
from stai.state import Repo

DISCLAIMER = (
    "AISHA is an educational capstone prototype. It is not affiliated with, "
    "endorsed by, or representative of BDO Unibank. All records, contacts, "
    "documents, metrics, and interactions in this demo are fictionalized."
)

app = FastAPI(
    title="AISHA - AI Support for Hires and Associates",
    description=DISCLAIMER,
    version="0.1.0",
)


# ------------------------------------------------------------- dependencies


@lru_cache(maxsize=1)
def get_repo() -> Repo:
    repo = Repo()
    repo.seed_if_empty()
    return repo


def get_agent_llm():
    """None means "use the default ChatOllama"; tests override with a fake."""
    return None


def get_guardrail_llm():
    """None means "use the default guardrail model"; tests override."""
    return None


# ------------------------------------------------------------------ schemas


class HistoryMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class ChatRequest(BaseModel):
    employee_id: str
    message: str = Field(min_length=1, max_length=4000)
    sim_date: date | None = None
    history: list[HistoryMessage] | None = None


class SourceOut(BaseModel):
    source: str
    title: str = ""
    snippet: str = ""


class ChatResponse(BaseModel):
    answer: str
    citations: list[str]
    sources: list[SourceOut]
    escalation_id: int | None
    plan_changed: bool
    guardrail_category: str
    refused: bool


class HealthResponse(BaseModel):
    status: str
    kb_ready: bool
    employees: int
    agent_model: str
    guardrail_model: str
    disclaimer: str


# ---------------------------------------------------------------- endpoints


@app.get("/health", response_model=HealthResponse)
def health(repo: Repo = Depends(get_repo)) -> HealthResponse:
    try:
        from stai.retriever import collection_count

        kb_ready = collection_count() > 0
    except Exception:
        kb_ready = False
    return HealthResponse(
        status="ok",
        kb_ready=kb_ready,
        employees=len(repo.list_employees()),
        agent_model=settings.agent_model,
        guardrail_model=settings.guardrail_model,
        disclaimer=DISCLAIMER,
    )


@app.post("/chat", response_model=ChatResponse)
def chat(
    req: ChatRequest,
    repo: Repo = Depends(get_repo),
    agent_llm=Depends(get_agent_llm),
    guardrail_llm=Depends(get_guardrail_llm),
) -> ChatResponse:
    employee = repo.get_employee(req.employee_id)
    if employee is None:
        raise HTTPException(status_code=404, detail=f"Unknown employee_id '{req.employee_id}'")

    sim_date = req.sim_date or date.today()
    if req.history is not None:
        history = [m.model_dump() for m in req.history]
    else:
        history = [
            {"role": m.role, "content": m.content}
            for m in repo.list_chat_messages(employee.id, limit=HISTORY_LIMIT)
        ]

    try:
        result = run_chat_turn(
            employee,
            repo,
            req.message,
            sim_date,
            history=history,
            route="api",
            llm=agent_llm,
            guardrail_llm=guardrail_llm,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=502,
            detail=(
                "Agent model call failed. Is Ollama running and is "
                f"'{settings.agent_model}' pulled? ({exc})"
            ),
        ) from exc

    repo.add_chat_message(employee.id, "user", req.message)
    repo.add_chat_message(
        employee.id,
        "assistant",
        result.answer,
        kind="refusal" if result.refused else "",
        sources=result.sources,
    )
    return ChatResponse(**result.model_dump())
